### ISSUE TITLE
Improper attribution

### ISSUE THREAD

**Issue by bradgessler** [radioactive-labs/phlexi-form#3]
Greetings!

I had somebody reach out to me thinking I contributed to this gem, but I'd never heard of it and haven't contributed. From what I can tell, this repo was copied into a new repo and not forked. Could you please do one of the following to minimize this confusion?

1. Create a fork and drop all of the upstream commits on top of it so Github picks it up.
2. Add a note to the README that this is a fork of superform.
3. Squash all of the prior commits and remove me from the git history.

Also, you removed my copyright from your LICENSE.txt file. If you keep this repo around you'll need to add my name back to the copyright, per this clause in the MIT License the repo you cloned:

> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

Ideally I'd like to see improvements rolled into a PR on Superform and committed upstream.

Thanks!

**Comment by thedumbtechguy** [comment]
Hello @bradgessler 
Thank you for bringing this to my attention.

1. Initially created a fork, but had to detach it. I forget what the actual issue was, but I was having some problem with Github.
2. I have added a note in the readme. Let me know if it is not sufficient.
3. I have squashed all previous commits, but it still is attributed to you. I renamed the commit to explain. Please let me know if that is insufficient.

The copyright has been restored. I initially performed a "find and replace" of all instances of your name. I apologize for that oversight.

Wrt to committing upstream, I unfortunately do not think the project fits what your goals for Superform are.
The project itself has changed so much I don't think there's a way to make that work.

Once again, I apologize for any inconvenience. This project would not even be a concept without your work on Superform.
Thank you!
